version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  build:
    commands:
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/lids/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
